// <auto-generated />
using System;
using GroceryStore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroceryStore.Infrastructure.Migrations
{
    [DbContext(typeof(GroceryDbContext))]
    partial class GroceryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("GroceryStore.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GroceryStore.Domain.Entities.ExternalProduct", b =>
                {
                    b.HasBaseType("GroceryStore.Domain.Entities.Product");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("GroceryStore.Domain.Entities.FreshFoodProduct", b =>
                {
                    b.HasBaseType("GroceryStore.Domain.Entities.Product");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("GroceryStore.Domain.Entities.InStockProduct", b =>
                {
                    b.HasBaseType("GroceryStore.Domain.Entities.Product");

                    b.HasDiscriminator().HasValue(1);
                });
#pragma warning restore 612, 618
        }
    }
}
